version: "3.3"
services:
  bazel-remote:
    container_name: bazel-remote-cache
    command:
      [
        "--max_size=50",
        "--experimental_remote_asset_api",
        "--host=0.0.0.0",
        "--profile_port=0",
      ]
    ports:
        - 9092:9092
    image: buchgr/bazel-remote-cache:v2.0.1
    user: $USER_ID:$GROUP_ID
    volumes:
      - $HOME/.cache/bazel/remote:/data:rw
